version: 1

formatters:
    simple:
        format: "%(levelname)s - %(funcName)s - %(lineno)d -  %(message)s"

    complex:
        format: "%(levelname)s - %(asctime)s - %(FuncName)s - %(lineno)d -  %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple

    file:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 5
        level: DEBUG
        formatter: simple
        filename : BtcApp.log

loggers:

    qsoWidget:
        level: INFO
        handlers: [console,file]
        propagate: yes

    __main__:   
        level: INFO
        handlers: [console]
        propagate: yes
